version: '3.7'

services:
  server:
    image: gisops/valhalla:latest
    deploy:
      labels:
        - 'traefik.enable=true'
        - 'traefik.http.routers.routing.entrypoints=web-secure'
        - 'traefik.http.routers.routing.rule=Host(`staging.${DOMAIN}`) && PathPrefix(`/service/routing`)'
        - 'traefik.http.services.routing.loadbalancer.server.port=8002'
        - 'traefik.http.routers.routing.middlewares=routing-prefix'
        - 'traefik.http.middlewares.routing-prefix.stripprefix.prefixes=/service/routing'
      mode: replicated
      replicas: 1
    ports:
      - 8072:8002
    environment:
      tile_urls: 'https://download.geofabrik.de/africa/nigeria-latest.osm.pbf'
      server_threads: 8
      use_tiles_ignore_pbf: 'True'
      build_elevation: 'True'
      build_admins: 'True'
      build_time_zones: 'True'
      build_tar: 'True'
      force_rebuild: 'False'
    volumes:
      - '${STORE_ROOT}/valhalla:/custom_files'
